randrproto: Fix missing #undef RRLease
clang did not like this, and it's hard to blame it:

../randr/randrstr.h:66:13: warning: redefinition of typedef 'CARD32' is a C11 feature [-Wtypedef-redefinition]
typedef XID RRLease;
            ^
/opt/X11/include/X11/extensions/randrproto.h:53:17: note: expanded from macro 'RRLease'
                ^
/opt/X11/include/X11/Xmd.h:111:23: note: previous definition is here
typedef unsigned long CARD32;

Signed-off-by: Adam Jackson <ajax@redhat.com>